foreground              #ffffff
background              #1e0000

background_opacity 0.7

selection_foreground    #1e1e2e
selection_background    #f5e0dc
url_color               #5d4bff

window_margin_width 7
wayland_titlebar_color system

close_on_exit true
font_family MesloLGS NF
allow_remote_control yes

include ~/.config/colors-s/colors-kitty.conf
